 List<String> keywords = [
  'not feeling well',
  'feeling sick',
  'sick',
  'do you do',
  'can you do',
  'greetings',
  'good morning',
  'who are you',
  'bisa',
  'fuck',
  'sorry',
  'hey',
  'give me a minute',
  'no',
  'let me think',
  'lemme think',
  'tell a joke',
  'where are you',
  'the weather',
  'you dance',
  'how old are you',
  'your role',
  'can you sing',
  'to a doctor',
  'are you angry',
  'latest news',
  '😂😂😂',
  '😂😂',
  'general health',
  'pregnancy',
  'covid-19',
  'sexual health',
  'HIV',
  'child health',
  'nutrition',
  'other',
  'yourself',
  'good health',
  'good',
  'do that',
  'thanks',
  'thank you',
   "hello",
  "how are you",
  "what's up",
  "tell me about yourself",
  "favorite color",
  "hobbies",
  "dream vacation",
  "healthcare",
  "medical advice",
  "symptoms",
  "healthy lifestyle",
  "nutrition tips",
  "exercise recommendations",
  "mental health",
  "healthy diet",
  "preventive care",
  "chronic conditions",
  "medication management",
  "stress management",
  "sleep hygiene",
  "emergency care",
  "vaccinations",
  "women's health",
  "men's health",
  "children's health",
  "elderly care",
  "pregnancy",
  "disease prevention",
  "health screenings",
  "holistic health",
  "alternative medicine",
  "rehabilitation",
  "physical therapy",
  "occupational therapy",
  "speech therapy",
  "home healthcare",
  "telemedicine",
  "health insurance",
  "healthcare costs",
  "hospital services",
  "urgent care",
  "pharmacy services",
  "patient advocacy",
  "end-of-life care",
  "grief support",
  "substance abuse",
  "smoking cessation",
   "consultation",
  "appointment scheduling",
  "prescription refill",
  "lab test results",
  "health tracker",
  "dietary restrictions",
  "allergies",
  "immunizations",
  "health education",
  "family history",
  "treatment options",
  "medication side effects",
  "therapy sessions",
  "work-life balance",
  "ergonomics",
  "injury prevention",
  "emergency preparedness",
  "smoking risks",
  "alcohol consumption",
  "drug interactions",
  "help",
  "doctor",
];

 List<String> responses = [
  'Sorry to hear that, Which of the following categories would you categorize your condition as: \nGeneral Health \nPregnancy \nCovid-19 \nSexual Health \nHIV \nChild Health \nNutrition \nOther',
  'Sorry to hear that, Which of the following categories would you categorize your condition as: \nGeneral Health \nPregnancy \nCovid-19 \nSexual Health \nHIV \nChild Health \nNutrition \nOther',
  'Sorry to hear that, Which of the following categories would you categorize your condition as: \nGeneral Health \nPregnancy \nCovid-19 \nSexual Health \nHIV \nChild Health \nNutrition \nOther',
  'I can tell a joke, refer you to a doctor if necessary and I\'m also available for a quick chat',
  'I can tell a joke, refer you to a doctor if necessary and I\'m also available for a quick chat',
  'Greetings! How can I be of service?',
  'Good morning! How can I be of service?',
  'I am a bot created by bisa Technologies to assist with your health related.How can I be of service?',
  'Bisa is a Tech company which provides IT solutions by creating top quality yet affordable, advanced software, specifically designed to meet the unique needs of its clients. The company is committed to building and developing technological solutions that ensure the continued competitiveness of businesses. Oasis Websoft also strives to keep the character of its software such that its ability to transform is clearly evidenced by persistent growth in every aspect of business.I am a bot created by bisa Technologies to assist with your health related.How can I be of service?',
  'No Comments.',
  'No worries.How else can I assist you?',
  'hey, how are you feeling today?',
  'Sure, I\'m always availabe here :)',
  'Understood. is there anything else you would like to share? if not you can tap the top chat icon to speak to a doctor',
  'Sure, I\'m always availabe here :)',
  'Sure, I\'m always availabe here :)',
  'Why did the scarecrow win an award? Because he was outstanding in his field.',
  'I exist in the virtual realm',
  'I can\'t provide real-time weather updates',
  'I can\'t dance, but I can help you with your health related issues :)',
  'I don\'t have an age, I\'m just a program. :)',
  'I\'m here to assist you in matters concerning your health. Do you have any health related issues?',
  'I can\'t sing, but I can help you with your health related issues :)',
  'You can tap the top chat icon to speak to a doctor.',
  'I\'m here to assist you, not to express my personal feelings.',
  'I don\'t experience time, so I don\'t know the latest news.',
  'They say laughter is the best medicine. but if you laugh too much, you might need medicine. 😂',
  'Glad to see you happy :)',
  'Understood, could you please tell me more about your current condition? or would you like to be referred to a doctor?',
  'Understood, could you please tell me more about your current condition? or would you like to be referred to a doctor?',
  'Sorry to here that, could you tell me more about your current condition? or would you like to be referred to a doctor?',
  'Sorry to here that, could you tell me more about your current condition? or would you like to be referred to a doctor?',
  'Sorry to here that, could you tell me more about your current condition? or would you like to be referred to a doctor?',
  'Understood, could you please tell me more about your current condition? or would you like to be referred to a doctor?',
  'Understood, could you please tell me more about your current condition? or would you like to be referred to a doctor?',
  'Understood, could you please tell me more about your current condition? or would you like to be referred to a doctor?',
  'Likewise, how can I be of service today?',
  'That\'s good to hear, I\' glad you are taking good care of yourself :)',
  'I\'m glad.',
  'do what?',
  'Always happy to help ☺️ . Need anything else?',
  'Always happy to help ☺️ . Need anything else?',
  "Hey there! 👋 What can I help you with today?",
  "I'm doing well, thank you for asking! How about you? 😊",
  "Not much, just here to chat and assist you. What's on your mind? 🗨️",
  "Sure! I'm here to help with any questions you have. But first, tell me a bit about yourself! 🤗",
  "I don't have a favorite color, but I'm here to provide colorful answers to your questions! 🎨",
  "I'm just a chatbot, so no hobbies for me. But I'm curious, what are your hobbies? 💬",
  "Dreaming of a vacation, huh? Tell me about your dream destination! 🌴",
  "Health is wealth! 💪 How can I assist you with your health concerns?",
  "I can provide some general advice, but remember, I'm not a doctor. For personalized advice, it's best to consult a healthcare professional. 💼. Tap on the chat icon on the top to speak to a doctor",
  "Feeling under the weather? Let's talk about your symptoms and see how I can help. 🤒",
  "Living a healthy lifestyle is key! How can I support you in your journey to better health? 🥦",
  "Eating right is important! Let's chat about some tasty and nutritious food options. 🥗",
  "Get moving and grooving! I can give you some exercise ideas to keep you active and energized. 🏃‍♂️",
  "Taking care of your mental health is just as important as physical health. Let's talk about how you're feeling. 💆‍♀️",
  "Food is fuel! Let's dish out some tips for a balanced and delicious diet. 🍽️",
  "Prevention is better than cure! Let's discuss some proactive steps to keep you healthy. 🛡️",
  "Dealing with a long-term condition? Let's chat about managing it effectively. 💼",
  "Juggling medications can be tricky. Let's make sure you're on the right track. 💊",
  "Stress happens to the best of us! Let's explore some stress-busting techniques. 🧘‍♂️",
  "Catch those Z's! Let's chat about improving your sleep quality. 😴",
  "In case of an emergency, I'm here to help guide you through what to do next. 🚑",
  "Vaccinations are like superheroes for your immune system! Let's make sure you're up-to-date. 💉",
  "Women's health matters! Let's talk about your health concerns and wellness goals. 👩‍⚕️",
  "Hey fellas, let's talk about keeping you in tip-top shape! 👨‍⚕️",
  "Kids' health is top priority! Let's chat about their growth and well-being. 👶",
  "Golden years should be golden! Let's talk about staying healthy and active as you age. 🌟",
  "Expecting? Congratulations! Let's chat about your journey to motherhood. 🤰",
  "Prevention is key! Let's discuss how to stay ahead of the health game. 🛡️",
  "Regular check-ups are a must! Let's chat about scheduling those screenings. 📅",
  "Mind, body, and soul! Let's explore holistic approaches to wellness. 🌿",
  "Sometimes, thinking outside the pillbox is good! Let's chat about alternative therapies. 💊",
  "Getting back on your feet? Let's talk about your road to recovery. 👟",
  "Move it, groove it! Let's chat about physical rehab strategies. 💪",
  "Occupational therapy is all about living life to the fullest! Let's discuss how it can help you. 🏋️‍♂️",
  "Finding your voice! Let's chat about speech therapy options. 🗣️",
  "Home sweet home! Let's explore healthcare options in the comfort of your own abode. 🏡",
  "Bringing the doctor to you! Let's chat about telemedicine services. 📱",
  "Navigating the world of health insurance? Let's break it down together. 💼",
  "Counting those coins? Let's discuss managing healthcare costs. 💰",
  "When in doubt, head to the hospital! Let's chat about hospital services. 🏥",
  "In a hurry? Urgent care has got your back! Let's talk about when to go. ⏱️",
  "Picking up prescriptions? Let's chat about pharmacy services. 💊",
  "Your health, your voice! Let's talk about patient advocacy. 📣",
  "End-of-life matters can be tough. Let's chat about your wishes and support options. ⌛",
  "Grieving is a journey. Let's chat about coping strategies and support networks. 🤝",
  "Struggling with substance use? Let's chat about getting the help you need. 💪",
  "Stub out that smoke! Let's chat about kicking the habit for good. 🚭",
  "Need a consultation? Let's chat about your healthcare needs! You can also tap on the chat icon to speak to a doctor 💬",
  "Want to schedule an appointment? I can help with that! 📅",
  "Running low on meds? Let's get that prescription refilled! 💊",
  "Curious about your lab results? Let's go over them together! 🧪",
  "Track your health goals with our handy health tracker! 📈",
  "Got any dietary restrictions? Let's make sure your meals fit your needs! 🥗",
  "Allergies acting up? Let's manage them together! 🤧",
  "Stay up-to-date with your immunizations! Let's discuss your vaccination schedule. 💉",
  "Education is key! Let's dive into some health education materials. 📚",
  "Know your family history? Let's talk about any genetic risks you should be aware of. 👨‍👩‍👦",
  "Exploring treatment options? Let's weigh the pros and cons together! ⚖️",
  "Experiencing medication side effects? Let's find a solution that works for you! 💊",
  "Ready for therapy? Let's schedule your sessions! 🛋️",
  "Striking a balance between work and life is essential! Let's talk about achieving harmony. ⚖️",
  "Ergonomics can make a big difference in your well-being! Let's optimize your workspace. 💼",
  "Prevent injuries with proper techniques and precautions! Let's chat about staying safe. 🚧",
  "Be prepared for emergencies! Let's create your emergency plan. 🚨",
  "Smoking poses serious risks to your health! Let's discuss quitting strategies. 🚭",
  "Monitor your alcohol consumption for a healthier lifestyle! Let's chat about moderation. 🍷",
  "Be cautious of drug interactions! Let's review your medications. ⚠️",
  'I can tell a joke, refer you to a doctor if necessary and I\'m also available for a quick chat',
  'You can tap the top chat icon to speak to a doctor.',
];