// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUgtk2RPudCEG6AgJHP2VzHtgDZzrZLKc',
    appId: '1:1008119938691:web:5e6b7b228e024789c725b6',
    messagingSenderId: '1008119938691',
    projectId: 'bisaapp-afb9b',
    authDomain: 'bisaapp-afb9b.firebaseapp.com',
    storageBucket: 'bisaapp-afb9b.appspot.com',
    measurementId: 'G-0CZBTG8LZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WLeFvghjvb_B9P-GZqakClNRMprx5Zo',
    appId: '1:1008119938691:android:23b8d4ee4d36ff35c725b6',
    messagingSenderId: '1008119938691',
    projectId: 'bisaapp-afb9b',
    storageBucket: 'bisaapp-afb9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_XAByDIk7AU_hZagbXpctLLBXj6sHo6w',
    appId: '1:1008119938691:ios:ae795274f21e83cbc725b6',
    messagingSenderId: '1008119938691',
    projectId: 'bisaapp-afb9b',
    storageBucket: 'bisaapp-afb9b.appspot.com',
    iosClientId: '1008119938691-gkt3gktld1109ao5fcfri57p5167gsdp.apps.googleusercontent.com',
    iosBundleId: 'gh.com.bisa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_XAByDIk7AU_hZagbXpctLLBXj6sHo6w',
    appId: '1:1008119938691:ios:329d200776a13c36c725b6',
    messagingSenderId: '1008119938691',
    projectId: 'bisaapp-afb9b',
    storageBucket: 'bisaapp-afb9b.appspot.com',
    iosBundleId: 'com.example.bisaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUgtk2RPudCEG6AgJHP2VzHtgDZzrZLKc',
    appId: '1:1008119938691:web:862e3fe0fa6675b7c725b6',
    messagingSenderId: '1008119938691',
    projectId: 'bisaapp-afb9b',
    authDomain: 'bisaapp-afb9b.firebaseapp.com',
    storageBucket: 'bisaapp-afb9b.appspot.com',
    measurementId: 'G-001712GMT3',
  );
}
